apiVersion: v1
kind: Service
metadata:
  name: web-service-kube
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80        # The port the Service listens on within the cluster
      targetPort: 80  # The port on the Pod to which traffic should be forwarded
  type: NodePort       # Expose service on a NodePort
